//
//  CardList.swift
//  
//
//  Created by Hugues Telolahy on 12/01/2023.
//
// swiftlint:disable line_length type_body_length

/// Bang cards list
enum CardList {
    
    static let abilities: [CardImpl] = [
        .init(name: .endTurn,
              type: .ability,
              onPlay: [Repeat(times: NumExcessHand(),
                              effect: Discard(card: CardSelectHand())),
                       SetTurn(player: PlayerNext())]),
        .init(name: .startTurn,
              type: .ability,
              triggers: [OnSetTurn()],
              onTrigger: [Repeat(times: NumExact(2),
                                 effect: DrawDeck())]),
        .init(name: .leaveGame,
              type: .ability,
              triggers: [OnLooseLastHealth()],
              onTrigger: [Eliminate()]),
        .init(name: .gameOver,
              type: .ability,
              triggers: [OnEliminated(), IsGameOver()],
              onTrigger: [EndGame()])
    ]
    
    static let collectibles: [CardImpl] = [
        .init(name: .beer,
              type: .action,
              canPlay: [IsPlayersAtLeast(3)],
              onPlay: [Heal(value: 1)]),
        .init(name: .saloon,
              type: .action,
              onPlay: [Heal(player: PlayerDamaged(),
                            value: 1)]),
        .init(name: .stagecoach,
              type: .action,
              onPlay: [Repeat(times: NumExact(2),
                              effect: DrawDeck())]),
        .init(name: .wellsFargo,
              type: .action,
              onPlay: [Repeat(times: NumExact(3),
                              effect: DrawDeck())]),
        .init(name: .generalStore,
              type: .action,
              onPlay: [Repeat(times: NumPlayers(),
                              effect: Store()),
                       DrawStore(player: PlayerAll(),
                                 card: CardSelectStore())]),
        .init(name: .catBalou,
              type: .action,
              playTarget: PlayerSelectAny(),
              onPlay: [Discard(player: PlayerTarget(),
                               card: CardSelectAny())]),
        .init(name: .panic,
              type: .action,
              playTarget: PlayerSelectAt(1),
              onPlay: [Steal(target: PlayerTarget(),
                             card: CardSelectAny())]),
        .init(name: .bang,
              type: .action,
              playTarget: PlayerSelectReachable(),
              canPlay: [IsTimesPerTurn(1)],
              onPlay: [ForceDiscard(player: PlayerTarget(),
                                    card: CardSelectHandNamed(.missed),
                                    otherwise: [Damage(player: PlayerTarget(), value: 1)])]),
        .init(name: .missed),
        .init(name: .gatling,
              type: .action,
              onPlay: [ForceDiscard(player: PlayerOthers(),
                                    card: CardSelectHandNamed(.missed),
                                    otherwise: [Damage(player: PlayerTarget(), value: 1)])]),
        .init(name: .indians,
              type: .action,
              onPlay: [ForceDiscard(player: PlayerOthers(),
                                    card: CardSelectHandNamed(.bang),
                                    otherwise: [Damage(player: PlayerTarget(), value: 1)])]),
        .init(name: .duel,
              type: .action,
              playTarget: PlayerSelectAny(),
              onPlay: [ChallengeDiscard(player: PlayerTarget(),
                                        challenger: PlayerActor(),
                                        card: CardSelectHandNamed(.bang),
                                        otherwise: [Damage(player: PlayerTarget(), value: 1)])]),
        .init(name: .barrel,
              type: .equipment,
              canPlay: [IsNotHavingSameCardInPlay()],
              triggers: [OnForceDiscardHandNamed(.missed)],
              onTrigger: [Luck(regex: CardRegex.successfulBarrel,
                               onSuccess: [Cancel()])]),
        .init(name: .jail,
              type: .handicap,
              playTarget: PlayerSelectAny(),
              canPlay: [IsTargetNotHavingSameCardInPlay()],
              triggers: [OnSetTurn()],
              onTrigger: [Luck(regex: CardRegex.escapeFromJail,
                               onSuccess: [Discard(card: CardPlayed())],
                               onFailure: [Discard(card: CardPlayed()),
                                           SetTurn(player: PlayerNext())])]),
        .init(name: .dynamite,
              type: .handicap,
              playTarget: PlayerSelectAny()),
        .init(name: .mustang,
              type: .equipment),
        .init(name: .scope,
              type: .equipment),
        .init(name: .schofield,
              type: .equipment),
        .init(name: .remington,
              type: .equipment),
        .init(name: .revCarabine,
              type: .equipment),
        .init(name: .winchester,
              type: .equipment),
        .init(name: .volcanic,
              type: .equipment)
    ]
    
    static let figures: [CardImpl] = [
        .init(name: .willyTheKid,
              type: .ability),
        .init(name: .roseDoolan,
              type: .ability),
        .init(name: .paulRegret,
              type: .ability),
        .init(name: .jourdonnais,
              type: .ability),
        .init(name: .slabTheKiller,
              type: .ability),
        .init(name: .luckyDuke,
              type: .ability),
        .init(name: .calamityJanet,
              type: .ability),
        .init(name: .bartCassidy,
              type: .ability),
        .init(name: .elGringo,
              type: .ability),
        .init(name: .suzyLafayette,
              type: .ability),
        .init(name: .vultureSam,
              type: .ability),
        .init(name: .sidKetchum,
              type: .ability),
        .init(name: .blackJack,
              type: .ability),
        .init(name: .kitCarlson,
              type: .ability),
        .init(name: .jesseJones,
              type: .ability),
        .init(name: .pedroRamirez,
              type: .ability)
    ]
    
    static let cardSets: [String: [String]] = [
        .barrel: ["Q♠️", "K♠️"],
        .dynamite: ["2♥️"],
        .jail: ["J♠️", "10♠️", "4♥️"],
        .mustang: ["8♥️", "9♥️"],
        .remington: ["K♣️"],
        .revCarabine: ["A♣️"],
        .schofield: ["K♠️", "J♣️", "Q♣️"],
        .scope: ["A♠️"],
        .volcanic: ["10♠️", "10♣️"],
        .winchester: ["8♠️"],
        .bang: ["A♠️", "2♦️", "3♦️", "4♦️", "5♦️", "6♦️", "7♦️", "8♦️", "9♦️", "10♦️", "J♦️", "Q♦️", "K♦️", "A♦️", "2♣️", "3♣️", "4♣️", "5♣️", "6♣️", "7♣️", "8♣️", "9♣️", "Q♥️", "K♥️", "A♥️"],
        .missed: ["10♣️", "J♣️", "Q♣️", "K♣️", "A♣️", "2♠️", "3♠️", "4♠️", "5♠️", "6♠️", "7♠️", "8♠️"],
        .beer: ["6♥️", "7♥️", "8♥️", "9♥️", "10♥️", "J♥️"],
        .catBalou: ["K♥️", "9♦️", "10♦️", "J♦️"],
        .duel: ["Q♦️", "J♠️", "8♣️"],
        .gatling: ["10♥️"],
        .generalStore: ["9♣️", "Q♠️"],
        .indians: ["K♦️", "A♦️"],
        .panic: ["J♥️", "Q♥️", "A♥️", "8♦️"],
        .saloon: ["5♥️"],
        .stagecoach: ["9♠️", "9♠️"],
        .wellsFargo: ["3♥️"]
    ]
}
