//
//  CardNames.swift
//  WildWestOnline
//
//  Created by Hugues Stéphano TELOLAHY on 14/07/2025.
//

// MARK: - Auras
public extension String {
    static let endTurn = "endTurn"
}

extension String {
    static let playMissedOnShot = "playMissedOnShot"
    static let discardExcessHandOnTurnEnded = "discardExcessHandOnTurnEnded"
    static let draw2CardsOnTurnStarted = "draw2CardsOnTurnStarted"
    static let nextTurnOnTurnEnded = "nextTurnOnTurnEnded"
    static let eliminateOnDamagedLethal = "eliminateOnDamagedLethal"
    static let endGameOnEliminated = "endGameOnEliminated"
    static let discardAllCardsOnEliminated = "discardAllCardsOnEliminated"
    static let nextTurnOnEliminated = "nextTurnOnEliminated"
    static let discardBeerOnDamagedLethal = "discardBeerOnDamagedLethal"
    static let draw3CardsOnEliminating = "draw3CardsOnEliminating"
    static let discardEquipedWeaponOnPrePlayed = "discardEquipedWeaponOnPrePlayed"
}

// MARK: - Collectible
public extension String {
    static let bang = "bang"
    static let missed = "missed"
    static let beer = "beer"
    static let saloon = "saloon"
    static let stagecoach = "stagecoach"
    static let wellsFargo = "wellsFargo"
    static let generalStore = "generalStore"
    static let catBalou = "catBalou"
    static let panic = "panic"
    static let gatling = "gatling"
    static let indians = "indians"
    static let duel = "duel"
    static let barrel = "barrel"
    static let dynamite = "dynamite"
    static let jail = "jail"
    static let schofield = "schofield"
    static let remington = "remington"
    static let revCarabine = "revCarabine"
    static let winchester = "winchester"
    static let volcanic = "volcanic"
    static let scope = "scope"
    static let mustang = "mustang"
    static let punch = "punch"
    static let dodge = "dodge"
    static let springfield = "springfield"
    static let hideout = "hideout"
    static let binocular = "binocular"
    static let whisky = "whisky"
    static let tequila = "tequila"
    static let ragTime = "ragTime"
    static let brawl = "brawl"
    static let lastCall = "lastCall"
    static let tornado = "tornado"
    static let backfire = "backfire"
    static let tomahawk = "tomahawk"
    static let aim = "aim"
    static let faning = "faning"
    static let saved = "saved"
    static let bandidos = "bandidos"
    static let poker = "poker"
    static let lemat = "lemat"
    static let shootgun = "shootgun"
    static let bounty = "bounty"
    static let rattlesnake = "rattlesnake"
    static let escape = "escape"
    static let ghost = "ghost"
}

// MARK: - Figures
public extension String {
    static let willyTheKid = "willyTheKid"
    static let roseDoolan = "roseDoolan"
    static let paulRegret = "paulRegret"
    static let jourdonnais = "jourdonnais"
    static let slabTheKiller = "slabTheKiller"
    static let luckyDuke = "luckyDuke"
    static let calamityJanet = "calamityJanet"
    static let bartCassidy = "bartCassidy"
    static let elGringo = "elGringo"
    static let suzyLafayette = "suzyLafayette"
    static let vultureSam = "vultureSam"
    static let sidKetchum = "sidKetchum"
    static let blackJack = "blackJack"
    static let kitCarlson = "kitCarlson"
    static let jesseJones = "jesseJones"
    static let pedroRamirez = "pedroRamirez"
    static let elenaFuente = "elenaFuente"
    static let seanMallory = "seanMallory"
    static let tequilaJoe = "tequilaJoe"
    static let pixiePete = "pixiePete"
    static let billNoface = "billNoface"
    static let gregDigger = "gregDigger"
    static let herbHunter = "herbHunter"
    static let mollyStark = "mollyStark"
    static let joseDelgado = "joseDelgado"
    static let chuckWengam = "chuckWengam"
    static let docHolyday = "docHolyday"
    static let apacheKid = "apacheKid"
    static let belleStar = "belleStar"
    static let patBrennan = "patBrennan"
    static let veraCuster = "veraCuster"
    static let coloradoBill = "coloradoBill"
    static let evelynShebang = "evelynShebang"
    static let lemonadeJim = "lemonadeJim"
    static let henryBlock = "henryBlock"
    static let blackFlower = "blackFlower"
    static let derSpotBurstRinger = "derSpotBurstRinger"
    static let tucoFranziskaner = "tucoFranziskaner"
}
